### ISSUE TITLE
Latest pull Still shows version 1.21

### ISSUE THREAD

**Issue by CriticalO** [flashnuke/wifi-deauth#15]
Hi there, just to let you know, I Git cloned this yesterday and the version number doesn't match the latest release. V2.3

Many thanks, I look forward to watching the development on this one, much appreciated :D

**Comment by flashnuke** [comment]
I forgot to update the version number when deploying, thanks for bringing this to my attention :)

addressed in https://github.com/flashnuke/wifi-deauth/pull/16 and deployed `v1.31`

**Comment by CriticalO** [comment]
You're very welcome thanks for some awesome coding ;)
